// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://asiwfehamcqhuujlsnyt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFzaXdmZWhhbWNxaHV1amxzbnl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNDE0NDksImV4cCI6MjA3NDcxNzQ0OX0.Hn7q1gWmMW6gaqAy2SgwHqfyuBAc3329qnFeagxCxBg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});